### ISSUE TITLE
defaultView not working

### ISSUE THREAD

**Issue by manurueda** [nhn/toast-ui.react-calendar#2] opened 2019-04-30 03:10 UTC
## Version
"@toast-ui/react-calendar": "^1.0.1"

## Test Environment
MAC OS Mojave 10.14.1

## Current Behavior
adding defaultView="month" does not show the month view as expected, it remains with the same view

```js
const AirworkCalendar = () => {
  return (
    <Calendar
      defaultView="month"
      usageStatistics={false}
      calendars={[
        {
          id: "0",
          name: "Private",
          bgColor: "#9e5fff",
          borderColor: "#9e5fff"
        }
      ]}
      disableDblClick={true}
      height="50vh"
      isReadOnly={true}
      month={{
        visibleWeeksCount: 3
      }}
      schedules={[
        {
          id: "1",
          calendarId: "0",
          title: "TOAST UI Calendar Study",
          category: "time",
          dueDateClass: "",
          start: changeTodayDateInDays(0),
          end: changeTodayDateInDays(3)
        }
      ]}
      template={{
        milestone(schedule) {
          return `<span style="color:#fff;background-color: ${
            schedule.bgColor
          };">${schedule.title}</span>`;
        }
      }}
      theme={myTheme}
      timezones={[
        {
          timezoneOffset: -420,
          displayLabel: "GMT-08:00",
          tooltip: "San Francisco"
        }
      ]}
    />
  );
};
```
This is an screenshot of the current behaviour
![image](https://user-images.githubusercontent.com/3317934/56939042-bc78b780-6aba-11e9-9553-38fd84880761.png)

## Expected Behavior
I would like to get the view like in the example https://nhn.github.io/tui.calendar/latest/tutorial-example05-3-weeks

**Comment by MikeAlvarado** [comment] 2019-05-16 18:11
Have you found any solution for this?
Having a button:
```
<button
    onClick={this.changeViewToWeek}
    > Month
</button>
```
with a function:
```
changeViewToWeek = () => {
    Calendar.changeView('day', true);
}
```
doesn't seems to work.

**Comment by MikeAlvarado** [comment] 2019-05-22 18:24
I was wondering if maybe you guys, @jung-han or @junghwan-park could look and take this issue. 

_Thanks in advance._

**Comment by MikeAlvarado** [comment] 2019-06-03 21:28
@jmderueda after ... _reading the Readme.md_ I finally managed to find out how to handle the events. 
First, you need to declare a referece. 
```
class ReactComponent extends Component {
  calendarRef = React.createRef(); //this line
  constructor(props) {
  ...
    };
  }
  ...
```   
and after that you just update the function with the reference.
```   
  changeViewToDay = () => {
    console.log("changingViewToDay");
    const calendarInstance = this.calendarRef.current.getInstance();
    calendarInstance.changeView('day', true);
    console.log("changeViewToDay");
  }
```

**Comment by lessfish** [comment] 2019-07-08 07:54
same problem, did I miss something? Or it's a real bug?

**Comment by MikeAlvarado** [comment] 2019-07-08 19:24
@lessfish, I've been working with the calendar for a while now, atm I don't think is possible to "render directly" to a view apart from week. 
The workaround for doing so is to call a function like above on `componentDidMount(){ }`

> --- after ... _reading the Readme.md_ I finally managed to find out how to handle the events.
> First, you need to declare a referece.
> 
> ```
> class ReactComponent extends Component {
>   calendarRef = React.createRef(); //this line
>   constructor(props) {
>   ...
>     };
>   }
>   ...
> ```
> 
> and after that you just update the function with the reference.
> 
> ```
>   changeViewToDay = () => {
>     console.log("changingViewToDay");
>     const calendarInstance = this.calendarRef.current.getInstance();
>     calendarInstance.changeView('day', true);
>     console.log("changeViewToDay");
>   }
> ```

**Comment by jungeun-cho** [comment] 2019-07-12 02:17
@jmderueda 
Use `view` prop instead of `defaultView` prop.
If you change the `view`("month", "week" or "day"), it will call `changeView` method internally.
```js
<Calendar
  view="month"
  ...
/>
```

**Comment by YEriin** [comment] 2019-07-12 03:39
> @jmderueda
> Use `view` prop instead of `defaultView` prop.
> If you change the `view`("month", "week" or "day"), it will call `changeView` method internally.
> 
> ```js
> <Calendar
>   view="month"
>   ...
> />
> ```

After set view = "month", the component display nothing. And, would you plz provide the *.d.ts file?

**Comment by jungeun-cho** [comment] 2019-07-12 03:53
@YEriin 
The `defaultProps` will be fixed soon. It will be declared as static.

The monthly calendar requires the height value of the container.

You can see [this](https://github.com/nhn/tui.calendar/blob/master/index.d.ts) for *.d.ts.

**Comment by jungeun-cho** [comment] 2019-07-12 06:04
@YEriin 
In the near future, I'll include a Typescript definition file in the wrapper.
Happy coding. ✨

**Comment by Giorat** [comment] 2019-09-04 09:54
@jungeun-cho how can I fix the error ''Setting defaultProps as an instance property on t is not supported and will be ignored.'' ?
```
<Calendar 
...
month = {
    {
        startDayOfWeek: 1,
        moreLayerSize: {
            width: "100%",
            height: "500px",
        }
    }
}
.../>
```
I tried with this but it didn't work.

**Comment by jungeun-cho** [comment] 2019-09-05 01:12
@Giorat Can you tell me how to reproduce the issue you mentioned?

**Comment by adhrinae** [comment] 2022-01-25 01:36
Closing the issue since it's inactive and the problem looks resolved.

**Closed by adhrinae** 2022-01-25 01:36 UTC
Labels: P❕❕, Bug
